# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: R

cache:
  packages: yes

sudo: false

#   Subdirectories containing R packages to be compiled
env:
  - PACK_DIR=macroutils

script: 
  - cd ./pkg/$PACK_DIR
  - ./travis-tool.sh install_github julienmoeys/macroutils/pkg/$PACK_DIR

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
 